### ISSUE TITLE
Does this take args for the ooba?

### ISSUE THREAD

**Issue by rafa-9** [ashleykleynhans/runpod-worker-oobabooga#1]
Some models need specific arguments like `--loader ExLlama` etc. Can we pass these through env variables? Also might be a good idea to be able to specify model from the env variables itself.

**Comment by ashleykleynhans** [comment]
This doesn't support loading models from environment variables, because it will dramatically impact the cold start times.  Its better to update the Docker image to specify the model that you want to use, and you can also add the additional arguments such as `--loader` to either `start_network_volume.sh` or `start_standalone.sh`, depending on whether you're using a Network volume or not.

**Comment by ashleykleynhans** [comment]
Example has been updated to include `--loader exllama`.
